version: '3.8'

services:
  tmux-mcp:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      # Mount tmux socket and config directory for persistence
      - tmux-socket:/tmp
      - tmux-data:/root/.tmux
    restart: unless-stopped

volumes:
  tmux-socket:
  tmux-data: